version: "3"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ./:/workspace
      - node_modules:/workspace/node_modules
volumes:
  node_modules: {}
